### ISSUE TITLE
pointent 

### ISSUE THREAD

**Issue by deronnax** [JulienPalard/poindent#1]
on vanilla Mac OS there is no 'tac' utils. Poindent does not detect it, goes on and display a successful progress bar

**Comment by JulienPalard** [comment]
Fixed in poindent v0.1.1, I do no longer use the shell and a `tac|tac` trick, I first open the file in Python, then read it, then pass it to msgcat:

```
with open(po_path, encoding='UTF-8') as po_file:
    po_content = po_file.read()
args = ['msgcat', '-', '-o', po_path]
if no_wrap:
    args[1:1] = ['--no-wrap']
run(args, universal_newlines=True, check=True, input=po_content)
```

Next trick to remove: don't rely on msgcat, rewrite it in Python, but that's another story for another day.

**Comment by deronnax** [comment]
didn't you tell me that indentation rules of gettext were out of this world and there was no point trying to reimplement them ?

**Comment by JulienPalard** [comment]
yup. for "another day" in "another galaxy".

Beware, I renamed poindent to powrap (`pip install powrap`).
